/* ===== SAMS Reports Module ===== */

class SamsReports {
    constructor() {
        this.formats = ['pdf', 'csv', 'json'];
    }
    
    // Generate event report
    generateEventReport(eventData, format = 'pdf') {
        switch(format) {
            case 'pdf':
                return this.generatePDF(eventData);
            case 'csv':
                return this.generateCSV(eventData);
            case 'json':
                return this.generateJSON(eventData);
            default:
                return this.generatePDF(eventData);
        }
    }
    
    // Generate PDF report
    generatePDF(data) {
        const report = {
            title: data.name,
            date: Utils.formatDate(data.date, 'long'),
            time: `${data.startTime} - ${data.endTime}`,
            location: data.location,
            totalStudents: data.totalStudents,
            present: data.present,
            absent: data.totalStudents - data.present,
            percentage: Utils.calculatePercentage(data.present, data.totalStudents),
            attendees: data.attendees || [],
            generatedAt: new Date().toISOString()
        };
        
        // Create HTML for PDF
        const html = `
            <!DOCTYPE html>
            <html>
            <head>
                <title>${report.title} - Attendance Report</title>
                <style>
                    body { font-family: Arial, sans-serif; padding: 20px; }
                    h1 { color: #2563eb; }
                    .header { margin-bottom: 30px; }
                    .stats { display: grid; grid-template-columns: repeat(3, 1fr); gap: 10px; margin: 20px 0; }
                    .stat { background: #f3f4f6; padding: 10px; border-radius: 5px; }
                    table { width: 100%; border-collapse: collapse; margin-top: 20px; }
                    th, td { padding: 8px; text-align: left; border-bottom: 1px solid #ddd; }
                    th { background: #2563eb; color: white; }
                    .footer { margin-top: 30px; font-size: 12px; color: #666; }
                </style>
            </head>
            <body>
                <div class="header">
                    <h1>${report.title}</h1>
                    <p>Date: ${report.date}</p>
                    <p>Time: ${report.time}</p>
                    <p>Location: ${report.location}</p>
                </div>
                
                <div class="stats">
                    <div class="stat">
                        <strong>Total Students:</strong> ${report.totalStudents}
                    </div>
                    <div class="stat">
                        <strong>Present:</strong> ${report.present}
                    </div>
                    <div class="stat">
                        <strong>Absent:</strong> ${report.absent}
                    </div>
                </div>
                
                <h3>Attendance Rate: ${report.percentage}%</h3>
                
                <table>
                    <thead>
                        <tr>
                            <th>Student</th>
                            <th>Registration</th>
                            <th>Sign Time</th>
                            <th>Status</th>
                        </tr>
                    </thead>
                    <tbody>
                        ${report.attendees.map(a => `
                            <tr>
                                <td>${a.name}</td>
                                <td>${a.regNumber}</td>
                                <td>${a.signTime || '-'}</td>
                                <td>${a.signTime ? 'Present' : 'Absent'}</td>
                            </tr>
                        `).join('')}
                    </tbody>
                </table>
                
                <div class="footer">
                    Generated by SAMS on ${Utils.formatDate(report.generatedAt, 'datetime')}
                </div>
            </body>
            </html>
        `;
        
        // Trigger print/save
        const printWindow = window.open('', '_blank');
        printWindow.document.write(html);
        printWindow.print();
        
        return report;
    }
    
    // Generate CSV report
    generateCSV(data) {
        const headers = ['Student Name', 'Registration', 'Sign Time', 'Status'];
        const rows = data.attendees.map(a => [
            a.name,
            a.regNumber,
            a.signTime || '',
            a.signTime ? 'Present' : 'Absent'
        ]);
        
        const csv = [
            headers.join(','),
            ...rows.map(row => row.join(','))
        ].join('\n');
        
        // Add summary at bottom
        const summary = [
            '',
            `Total Students,${data.totalStudents}`,
            `Present,${data.present}`,
            `Absent,${data.totalStudents - data.present}`,
            `Attendance Rate,${Utils.calculatePercentage(data.present, data.totalStudents)}%`
        ].join('\n');
        
        return csv + summary;
    }
    
    // Generate JSON report
    generateJSON(data) {
        return {
            metadata: {
                generatedAt: new Date().toISOString(),
                version: CONFIG.version
            },
            event: {
                id: data.id,
                name: data.name,
                date: data.date,
                startTime: data.startTime,
                endTime: data.endTime,
                location: data.location
            },
            summary: {
                totalStudents: data.totalStudents,
                present: data.present,
                absent: data.totalStudents - data.present,
                percentage: Utils.calculatePercentage(data.present, data.totalStudents)
            },
            attendance: data.attendees || []
        };
    }
    
    // Generate monthly summary
    generateMonthlySummary(courseId, month, year) {
        // Mock data - replace with actual
        return {
            course: courseId,
            month: month,
            year: year,
            totalEvents: 22,
            totalAttendance: 450,
            possibleAttendance: 495,
            rate: 91,
            students: [
                { name: 'John Doe', present: 20, missed: 2, rate: 91 },
                { name: 'Jane Smith', present: 22, missed: 0, rate: 100 }
            ]
        };
    }
    
    // Export to file
    exportReport(data, format, filename) {
        let content = '';
        let type = '';
        
        switch(format) {
            case 'csv':
                content = this.generateCSV(data);
                type = 'text/csv';
                filename = filename || `report-${Date.now()}.csv`;
                break;
            case 'json':
                content = JSON.stringify(this.generateJSON(data), null, 2);
                type = 'application/json';
                filename = filename || `report-${Date.now()}.json`;
                break;
            case 'pdf':
                // PDF handled separately
                return;
        }
        
        Utils.downloadFile(content, filename, type);
    }
    
    // Send report via WhatsApp
    async sendReportViaWhatsApp(whatsapp, reportData, format = 'csv') {
        const report = this.generateJSON(reportData);
        const summary = `
SAMS Attendance Report
Event: ${report.event.name}
Date: ${report.event.date}
Present: ${report.summary.present}/${report.summary.totalStudents}
Rate: ${report.summary.percentage}%
        `;
        
        return Notifications.sendWhatsApp(whatsapp, summary);
    }
}

// Initialize
const Reports = new SamsReports();
